---
- name: Wait until initial admin password is appear
  register: is_find_init_token
  ansible.builtin.wait_for:
    timeout: 120
    path: /var/lib/jenkins/secrets/initialAdminPassword

- name: Retry for expose initial password
  when: task_install_changed | bool or not is_find_init_token.failed
  block:
    - name: Get initial admin password
      ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_admin_password
      changed_when: false
    - name: Initial admin password is
      ansible.builtin.debug:
        msg: "{{ jenkins_initial_admin_password.stdout }}"
    - name: Write admin password to File
      ansible.builtin.copy:
        content: "{{ jenkins_initial_admin_password.stdout }}"
        dest: /tmp/inti_password.txt
      delegate_to: localhost
    - name: try get admin password from create file
      ansible.builtin.command: cat /tmp/inti_password.txt
      register: jenkins_initial_admin_password_from_file
      delegate_to: localhost
    - name: Initial admin password is
      ansible.builtin.debug:
        msg: "{{ jenkins_initial_admin_password_from_file.stdout }}"