---
- name: Run role
  hosts: all
  become: yes
  become_method: su
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: install jenkins standar dep (RedHat)
      when: ansible_os_family == "RedHat"
      ansible.builtin.yum:
        name: initscripts
        state: latest
  roles:
    - opsta.java
    - ansible-jenkins
